### ISSUE TITLE
Admin Side pages with HTML issues 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#5807]
- [x] Developer's Toolkit.  (original issue #5540)
- [x] Invoice (original issue #5520)
- [ ] Options Value Manager (original issue #5424)

**Comment by brittainmark** [comment]
developer's toolkit needs ticking above.
